name: Node.js CI
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Run build script
      run: |
        npm i
        zip -r build.zip node_modules heroes

    - name: Copy files to bucket with the AWS CLI
      run: |
        aws s3 cp build.zip s3://marvel